from api.models.portfolio import Portfolio, Position


def get_portfolio() -> Portfolio:
    return Portfolio(
        positions=[
            Position(
                symbol="AAPL",
                name="Apple Inc.",
                quantity=120,
                average_cost=168.40,
                market_value=21480.0,
                pl_percent=4.2,
                urgency="urgent",
            ),
            Position(
                symbol="MSFT",
                name="Microsoft",
                quantity=80,
                average_cost=310.20,
                market_value=25200.0,
                pl_percent=-1.1,
                urgency="attention",
            ),
            Position(
                symbol="UBSG",
                name="UBS Group",
                quantity=1382819,
                average_cost=23.50,
                market_value=183217.0,
                pl_percent=2718211.72,
                currency="CHF",
                urgency="stable",
            ),
            Position(
                symbol="BTC",
                name="Bitcoin",
                quantity=2,
                average_cost=45000.00,
                market_value=95000.0,
                pl_percent=5.6,
                urgency="stable",
            ),
            Position(
                symbol="TSLA",
                name="Tesla Inc.",
                quantity=50,
                average_cost=200.00,
                market_value=12500.0,
                pl_percent=-2.3,
                urgency="stable",
            ),
            Position(
                symbol="GOOGL",
                name="Alphabet Inc.",
                quantity=30,
                average_cost=140.00,
                market_value=4500.0,
                pl_percent=7.1,
                urgency="stable",
            ),
            Position(
                symbol="AMZN",
                name="Amazon.com Inc.",
                quantity=25,
                average_cost=150.00,
                market_value=4000.0,
                pl_percent=6.7,
                urgency="stable",
            ),
            Position(
                symbol="NVDA",
                name="NVIDIA Corporation",
                quantity=15,
                average_cost=400.00,
                market_value=7500.0,
                pl_percent=25.0,
                urgency="stable",
            ),
            Position(
                symbol="ETH",
                name="Ethereum",
                quantity=10,
                average_cost=3000.00,
                market_value=35000.0,
                pl_percent=16.7,
                urgency="stable",
            ),
        ]
    )
